#!/usr/bin/python3
import sys


def factoriztion(num):
    for i in range(2, num):
        if num % i == 0:
            return i
    return 1

def main():
    try:
        source = sys.argv[1]
        f = open(source, 'r');
        for line in f.readlines():
            div = 1
            print("{:d}={:d}*{:d}".format(int(line), int(int(line)/div), div))
        f.close()
    except Exception:
        pass
main()
