#!/usr/bin/python3
import sys

source = sys.argv[1]
primes = []

def prime():
    lprimes = [True for i in range(int(1e18+1))]
    p = 2
    while p*p <= (int(1e18+1)):
        if lprime[p]:
            primes.append(p)
            j = p*p
            while j*j <= (int(1e18+1)):
                lprimes[j] = False
                j += p
        p = p + 1

def factoriztion(num):
    prime()
    for i in primes:
        print("{} ".format(i), end="")

def main():
    f = open(source, 'r');
    for line in f.readlines():
        div = factoriztion(int(line))
        print("{:d}={:d}*{:d}".format(int(line), int(int(line)/div), div))
    f.close()
factoriztion(5);
